### ISSUE TITLE
Response status code does not indicate success: 403 (rate limit exceeded).

### ISSUE THREAD

**Issue by biggievan** [mattpannella/pocket-updater-utility#121]
I keep getting Response status code does not indicate success: 403 (rate limit exceeded) when running the pocket_updater (mac version).

**Comment by biggievan** [comment]
Looks like an out of date updater

**Comment by mattpannella** [comment]
you're hitting the github api rate limit. try again in an hour

**Comment by biggievan** [comment]
Thank you. Do you know why I am getting this error?

Update Process Complete
Assets Not Found:
/Assets/pcecd/common/bios_1_0_usa.pce
/Assets/pcecd/Mazamars312.PC Engine CD/mpu.bin

Thank you so much for your work on the pocket updater. Is there a way we can kick you some $$

Michael...

**Comment by mattpannella** [comment]
the first one is because we weren't able to find a copy of that bios that the core lists in its definition files. its not an issue really
but the 2nd one it looks like you deleted a required file in the core. if you delete the folder /Cores/Mazamars312.PC Engine CD and run the updater again it should restore that file

**Comment by mattpannella** [comment]
i have a paypal link in the readme for this project if you want to donate

**Comment by biggievan** [comment]
Done. Thanks again for your help and work on this project.

Michael
