### ISSUE TITLE
Remove bad files before install

### ISSUE THREAD

**Issue by LoneBoco** [mattpannella/pocket-updater-utility#72]
Some cores, like the Jotego ones, are often packaged bad and included Mac OSX folders and whatnot inside them.  A good new feature would be to sanitize the files that are installed to ignore any bad files or directories.

When the zip file is extracted into a temporary directory, the software could go through and sanitize things a bit.  Delete all the .DS_Store directories and anything that we know will not be handled properly by the Pocket.

**Comment by Tolaris** [comment]
Here's what I use to sanitise my filesystem after pocket_updater runs:

`find -name .??* -exec rm {} \;`

As you can probably guess, I run Linux full time, don't even have a Windows build environment. Perhaps we want a powershell way to do this?

**Comment by mattpannella** [comment]
the mac os files in that jotego core are a bit of an outlier. i manually updated one of those mirror'd jotego zips because he didnt include all the files. but normally this stuff is all build via github actions and should never contain that stuff

as far as other files (readmes, mras etc) yeah. i've been putting off dealing with that since day 1 haha. should probably just get around to changing the process so it extracts and then pulls the 4 folders out, instead of blindly extracting the zip onto the sd card

**Comment by Tolaris** [comment]
I did clean those (and many other minor irritants) up by hand after extraction, and I have a helper CLI that removes the various dotfile cruft that is often also in the ZIPs (.git, .keep, .__MACOSX, etc). We should definitely extract to a temp directory and then move only what we need, then purge the folder.

**Comment by LoneBoco** [comment]
I went ahead and implemented something to clean up bad files.  This mostly cleans up the Jotego cores.  It can't resolve the issue with jtvigil where duplicate assets are installed, so something like that would need further development.  But this should help a lot.

**Comment by Tolaris** [comment]
Bonus points for "fast and good enough". 😁

Off-topic: where can I file bugs against the Jotego cores? Example: Roc'n
Rope is rotated 90° and has no DIP switch options on Pocket.
